### ISSUE TITLE
Synchronization issue?

### ISSUE THREAD

**Issue by rahsharmar** [mpc-msri/EzPC#2] opened 2019-07-02 11:50 UTC
The behavior of output changes according to whether I provide server inputs first or client inputs first. Sometimes the outputs are shown only to client with ALL if server inputs are provided first.

**Comment by nishkum** [comment] 2019-07-02 12:05
Can you please post an ezpc code snippet which reproduces this?

**Comment by rahsharmar** [comment] 2019-07-02 12:06
The docker example

**Comment by nishkum** [comment] 2019-07-02 18:32
Closing this as the problem was with the script to run the example.

**Closed by nishkum** 2019-07-02 18:32 UTC
